apiVersion: v1
kind: Service
metadata:
  name: welcomer
  namespace: hackerspace
  labels:
    app: welcomer
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: welcomer